<?php

 
function dtbx_admincontrol_menu() 
{
    $items['dtbx_admincontrol'] = array(
        'title' => 'Администрирование',
        'access callback' => true,
        'page callback' => 'drupal_get_form',
		'page arguments' => array('dtbx_admincontrol_page'),		
        'type' => MENU_CALLBACK,
    );
	
	return $items;
}

function dtbx_admincontrol_page($form, &$form_state) 
{
	global $user;
	module_load_include('pages.inc', 'user');

	
		$form['company']['table'] = array(
			'#tree' => TRUE,
			'#theme' => 'dtbx_privateroom_table',
			'#prefix' => '<div class="table-view search-page">',
			'#suffix' => '</div>',			
		);	  
	
		$form['company']['table']['header'] = array(
			'#type' => 'value',
			'#value' => array('', 'ID', 'Фирма', 'Адрес', 'ИНН', 'Активен', 'Активен до', ''),
		);
  
		$qcompany = db_query("select c.*, aa.* from t_company c
						left join (select 	a.address_id as actual_address_id,
											r.region_name as actual_region_name, 
											ct.city_name as actual_city_name,
											a.street_name as actual_street_name, 
											a.house_number as actual_house_number,
											a.region_id as actual_region_id,
											a.city_id as actual_city_id
									  from 	t_address a,
											t_region r,
											t_city ct
									  where a.region_id = r.region_id and
											a.city_id = ct.city_id) aa on aa.actual_address_id = c.company_actual_address_id");
 
		foreach ($qcompany as $rec) {
				$form['company']['table']['data'][$rec->company_id][] = array(
					'#markup' => '',
					'#attributes' => array('class' => array('first'))
				);
				$form['company']['table']['data'][$rec->company_id]['company_id'] = array(
					'#markup' => $rec->company_id,
				);
				$form['company']['table']['data'][$rec->company_id][] = array(
					'#markup' => $rec->company_name,
				);
				
				$address = $rec->actual_region_name . (($rec->actual_city_name != "") ? (', ' . $rec->actual_city_name) : '') . 
							(($rec->actual_street_name != "") ? ('<br>' . $rec->actual_street_name) : '') . 
							(($rec->actual_house_number != "") ? (' ' . $rec->actual_house_number) : '');
				
				$form['company']['table']['data'][$rec->company_id][] = array(
					'#markup' => $address,
				);
				
				$form['company']['table']['data'][$rec->company_id][] = array(
					'#markup' => $rec->company_inn,
				);
	 
				$form['company']['table']['data'][$rec->company_id]['flag_post_pl'] = array(
					'#type' => 'checkbox',
					'#default_value' => $rec->flag_post_pl
				);
				
				$exp_date = explode('-', $rec->company_expired_date);

				$form['company']['table']['data'][$rec->company_id]['exp_date'] = array(
					'#type' => 'date',
					'#default_value' =>  (count($exp_date) == 3 ? array('year' => $exp_date[0], 'month' => intval($exp_date[1]), 'day'=> intval($exp_date[2])) : 0)
				);
		}
		
		$form['company']['submit'] = array(
			'#type' => 'submit', 
			'#value' => t('Сохранить'),
			'#submit' => array('dtbx_admincontrol_submit'),	
		);
	return $form;
}




 
function dtbx_admincontrol_submit($form, &$form_state) 
{
	foreach ($form_state['values']['table']['data'] as $key => $value) {
		$date = $value['exp_date']['year'] . '-' . $value['exp_date']['month'] . '-' . $value['exp_date']['day'];
		$query = 'update t_company set flag_post_pl = ' . $value['flag_post_pl'] . ', company_expired_date = \'' . $date . '\' where company_id = ' . $key;
		db_query($query);
	}
	return $form;
}

?>

