<?php

/**
 * init().
 */

  
function dtbx_sellerinfo_init() {
	static $already_added = FALSE;
		drupal_add_js('http://api-maps.yandex.ru/2.0-stable/?load=package.standard&lang=ru-RU', 'external');
		drupal_add_js('misc/geo.js', 'file');
		
	if ($already_added) {
		return; 
	}	  
	$already_added = TRUE;
}

/**
 * Implements hook_menu().
 */
 
function dtbx_sellerinfo_menu() 
{
    $items['dtbx_sellerinfo/%'] = array(
        'title' => 'Данные продавца',
        'access callback' => true,//'dtbx_sellerinfo_access',
        'page callback' => 'drupal_get_form',
		'page arguments' => array('dtbx_sellerinfo_page', 1),		
        'type' => MENU_CALLBACK,
    );
	return $items;
}

function dtbx_sellerinfo_page($form, &$form_state, $sellerid) 
{
	$form = array();
	
	$str_query = 'select * from t_user where user_id = ' . $sellerid;
	$items = db_query($str_query)->fetchObject();    
	
	
	$surname = "";
	$firstname = "";
	$patronname = "";
	$companyname = "";
	$juraddress = "";
	$realaddress = "";
	$contact = "";
	$profile = "Контакты";
	$responce = "Отзывы";
	
	
	if(count($items) > 0)
	{
		$surname = $items->user_surname;
		$firstname = $items->user_name;
		$patronname = $items->user_patronymic;
		$companyname = $items->company_name;
		$juraddress = $items->company_address;
		$realaddress = $items->company_actual_address;
		$contact = $items->company_contact;
		//$persondata .= $items->USER_LOGIN;
	}
  
//
  $form['profile'] = array(
    '#type' => 'fieldset', 
    '#title' => t($profile), 
  ); 
 
//
	
  /*
  $map = ('	
			<script src="http://api-maps.yandex.ru/2.0-stable/?load=package.standard&lang=ru-RU" type="text/javascript"></script>
			<script src="http://detbox.ru/misc/geo.js"  type="text/javascript"></script>
			<script type="text/javascript">showmap(\'' . $juraddress . '\')</script>
			<div id="map" style="width: 400px; height: 250px; border: 1px double black;"></div>
		 ');
  */
  
  $map = ('	<script type="text/javascript">showmap(\'' . $juraddress . '\')</script>
			<div id="map" style="width: 400px; height: 250px; border: 1px double black;"></div>');
	
  //$map = ('	<div id="map" style="width: 400px; height: 250px; border: 1px double black;"></div>');
 
  //drupal_set_message($map, 'status') ;
  $output = '
		<table width=100%>
		<tr><td style="vertical-align: top">Название компании</td><td style="vertical-align: top">' . $companyname . '</td><td rowspan=3> ' . $map . '</td></tr>
		<tr><td style="vertical-align: top">Адрес компании</td><td style="vertical-align: top">' . $juraddress . '</td></tr>
		<tr><td style="vertical-align: top">Контактное лицо</td><td style="vertical-align: top">' . $contact . '</td></tr>
		</table>
  ';
  
  
  
  $form['profile']['table'] = array(
    '#markup' => $output
  );
  
  $form['responce'] = array(
    '#type' => 'fieldset', 
    '#title' => t($responce), 
  );
   
   
  if (dtbx_sellerinfo_access()) {
	
  
	$form['responce']['responce_text'] = array(
      '#type' => 'textarea',
	  '#title' => t('Ваше мнение:'),      
      '#rows' => 10,
      '#cols' => 10,
	  '#default_value' => '1', 
      '#resizable' => TRUE,
    );
    
	
    $form['responce']['shopid'] = array(
      '#type' => 'hidden',
      '#value' =>  $items->user_id,
    );
	
	$form['responce']['rating']= array(
	  '#type' => 'radios',
	  '#title' => t('рейтинг'),
	  '#options' => array(t('1'), t('2'), t('3'), t('4'), t('5')),
	  /*'#prefix' => '<div class="container-inline">',
	  '#suffix' => '</div>',*/
    );
	
    $form['responce']['submit'] = array(
	  '#type' => 'submit', 
	  '#value' => t('Добавить отзыв'), 
	  '#submit' => array('dtbx_sellerinfo_submit'),
    );
  
  } 
    
	$records = db_query("SELECT * 
					  FROM t_review tr 
					  WHERE tr.to_user_id = :uid
					  order by review_date desc
					  ", array(':uid' => $items->user_id));
					  
	$output = '<div class="table-view search-page" style=" height: 150px; overflow: auto"><table><tr><th>Рейтинг</th><th>&nbsp;&nbsp;&nbsp;Дата</th><th>Сообщение</th></tr>';
	foreach ($records as $rec) {
	
		$output .= ('<tr><td>' . $rec->review_rating . '</td><td>' . $rec->review_date . '</td><td>' . $rec->review_text . '</td></tr>');
		
	}
	$output .= "</table></div>";
	
	$form['responce']['table2'] = array(
		'#markup' => $output
	);
  
  return $form;
}


/**
* Page access.
**/

function dtbx_sellerinfo_access() {
  global $user;
  return ($user->uid > 0);
}

function dtbx_sellerinfo_submit($form, &$form_state)
{
  global $user;
  db_query('INSERT INTO t_review (review_date, from_user_id, to_user_id, review_text, review_rating)
			VALUES (:review_date, :from_user_id, :to_user_id, :review_text, :review_rating + 1)', 
 			array(':review_date' => date("Y-m-d H:i:s", time()), 
				  ':from_user_id' => $user->uid,
   				  ':to_user_id' => $form_state['values']['shopid'],
				  ':review_text' => $form_state['values']['responce_text'],
				  ':review_rating' => $form_state['values']['rating']));

  drupal_set_message(t('Отзыв добавлен.'));
  $form_state['rebuild'] = true;
  cache_clear_all();					
return $form;
}


?>