<?php

/**
 * init().
 */

  
function dtbx_sellerinfo_init() {
	static $already_added = FALSE;
		drupal_add_js('http://api-maps.yandex.ru/2.0-stable/?load=package.standard&lang=ru-RU', 'external');
		drupal_add_js('misc/geo.js', 'file');
		
	if ($already_added) {
		return; 
	}	  
	$already_added = TRUE;
}

/**
 * Implements hook_menu().
 */
 
function dtbx_sellerinfo_menu() 
{
    $items['dtbx_sellerinfo/%'] = array(
        'title' => 'Данные продавца',
        'access callback' => true,//'dtbx_sellerinfo_access',
        'page callback' => 'drupal_get_form',
		'page arguments' => array('dtbx_sellerinfo_page', 1),		
        'type' => MENU_CALLBACK,
    );
	return $items;
}

function dtbx_sellerinfo_page($form, &$form_state, $sellerid) 
{
	$form = array();
	
	
	$qcompany = db_query('select c.*,
								 la.*,
								 aa.*
						from t_company c
						left join (select 	a.address_id as legal_address_id,
											r.region_name as legal_region_name, 
											ct.city_name as legal_city_name,
											a.street_name as legal_street_name, 
											a.house_number as legal_house_number												
									  from 	t_address a,
											t_region r,
											t_city ct
									  where a.region_id = r.region_id and
											a.city_id = ct.city_id) la on la.legal_address_id = c.company_legal_address_id
											  
						left join (select 	a.address_id as actual_address_id,
											r.region_name as actual_region_name, 
											ct.city_name as actual_city_name,
											a.street_name as actual_street_name, 
											a.house_number as actual_house_number											
									  from 	t_address a,
											t_region r,
											t_city ct
									  where a.region_id = r.region_id and
											a.city_id = ct.city_id) aa on aa.actual_address_id = c.company_actual_address_id
						where c.company_id = :company_id', array(':company_id' => $sellerid))->fetchObject();
	
	
	$companyname = "";
	$companyogrn = "";
	$companyinn = "";
	$companyboss = "";
	$companybuh = "";
	$companybank = "";
	$companyla = "";
	$companyaa = "";
	$comapnyrating = 0;
	
	$fdealer = 0;
	$fvin = 0;
	$fonline = 0;
	$frepair = 0;
	$fretailing = 0;
	$fwholesale = 0;
	$fcourier = 0;
	$fregion = 0;
	
	$profile = "Контакты:";
	$responce = "Отзывы:";
	
	
	if (is_object($qcompany) > 0) {
		$companyname = $qcompany -> company_name;
		$companyogrn = $qcompany -> company_ogrn;
		$companyinn = $qcompany -> company_inn;
		$companyboss = $qcompany -> company_boss;
		$companybuh = $qcompany -> company_buh;
		$companybank = $qcompany -> company_bank_details;
		$companyla = $qcompany -> legal_region_name . ', ' . $qcompany -> legal_city_name . ', ' . $qcompany -> legal_street_name . ', ' . $qcompany -> legal_house_number;
		$companyaa = $qcompany -> actual_region_name . ', ' . $qcompany -> actual_city_name . ', ' . $qcompany -> actual_street_name . ', ' . $qcompany -> actual_house_number;
		$comapnyrating = $qcompany -> company_rating;
		
		$fdealer = $qcompany -> flag_dealer;
		$fvin = $qcompany -> flag_in_vin;
		$fonline = $qcompany -> flag_online_store;
		$frepair = $qcompany -> flag_repair;
		$fretailing = $qcompany -> flag_retailing;
		$fwholesale = $qcompany -> flag_wholesale;
		$fcourier = $qcompany -> flag_courier;
		$fregion = $qcompany -> flag_send_region;
	}
  
//
  $form['profile'] = array(
    '#type' => 'fieldset', 
    '#title' => '', 
	
  ); 
 
//
	
  /*
  $map = ('	
			<script src="http://api-maps.yandex.ru/2.0-stable/?load=package.standard&lang=ru-RU" type="text/javascript"></script>
			<script src="http://detbox.ru/misc/geo.js"  type="text/javascript"></script>
			<script type="text/javascript">showmap(\'' . $juraddress . '\')</script>
			<div id="map" style="width: 400px; height: 250px; border: 1px double black;"></div>
		 ');
  */
  
  $map = ('	<script type="text/javascript">showmap(\'' . $companyaa . '\')</script>
			<div id="map" style="width: 400px; height: 250px; border: 1px double black;"></div>');
	
  //$map = ('	<div id="map" style="width: 400px; height: 250px; border: 1px double black;"></div>');
 
  //drupal_set_message($map, 'status') ;
  	$records = db_query('select ci.company_info_type_id,
								ci.company_info_type_name
						 from t_company_info_type ci
						 order by ci.company_info_type_id');
	
	$cntrec = 2 + $records->rowCount();	
	
	$i = 0;
	$star = '';
			
	while ($i++ < $comapnyrating) {
		$star .= '<img src="sites\all\themes\detbox\icons\startgold@2x.png">&nbsp';
	}
			
	$i = 0;
	while ($i++ < (5 - $comapnyrating)) {
		$star .= '<img src="sites\all\themes\detbox\icons\stargrey@2x.png">&nbsp';
	}
	
	$form['title'] = array(
		'#type' => 'value',
		'#value' => $companyname . '&nbsp&nbsp' . $star
	);
	
	$output = '
		<table class="table-contact">
		<tr><td class="head">Адрес компании</td><td>' . $companyaa . '</td><td rowspan=' . $cntrec .'> ' . $map . '</td></tr>';
	
	foreach($records as $rec) {
		$output .= '<tr><td class="head">' . $rec->company_info_type_name . '</td><td>';
		$qcontacts = db_query('select cil.company_info_value
								 from t_company_info_link cil
								where cil.company_info_type_id = :company_info_type_id and
									  cil.company_id = :company_id',
							  array(
								':company_info_type_id' => $rec -> company_info_type_id,
								':company_id' => $sellerid
								)
							  );
		foreach ($qcontacts as $qcontact){
			$output .= $qcontact-> company_info_value . '<br>';
		}
		$output .= '</td></tr>';
	}		
		
	$output .= '<tr><td class="head">Дополнительно:</td><td>';

	$output .= ($fdealer == 1) 		? 'Официальный дилер, ' 	: null;
	$output .= ($fvin == 1) 		? 'Запросы по VIN, ' 		: null;
	$output .= ($fonline == 1) 		? 'Есть интернет-магазин, '	: null;
	$output .= ($frepair == 1) 		? 'Есть СТО, '				: null;
	$output .= ($fretailing == 1) 	? 'Торговля в розницу, '	: null;
	$output .= ($fwholesale == 1) 	? 'Торговля оптом, '		: null;
	$output .= ($fcourier == 1) 	? 'Доставка курьером, '		: null;
	$output .= ($fregion == 1) 		? 'Доставка в регионы, '	: null;

	$output .= '</td></tr></table>';
  
  
  
  $form['profile']['table'] = array(
    '#markup' => $output
  );
  
  $form['responce'] = array(
    '#type' => 'fieldset', 
    '#title' => '',
  );

  $form['responce']['lreview'] = array(
    '#type' => 'item', 
    '#title' => t($responce),
	'#prefix' => '<br><span class="lreview">',
	'#suffix' => '</span>'
  );
  
   
   $records = db_query("select 	tr.review_id,
								DATE_FORMAT(tr.review_date, '%d.%m.%Y %h:%i') as review_date,
								tr.user_id,
								tr.company_id,
								tr.review_text,
								tr.review_rating  
						from t_review tr 
						where tr.company_id = :company_id
						order by tr.review_date desc
					  ", array(':company_id' => $sellerid));
					  
	$output = '<div class="table-view search-page" style="max-height: 196px; overflow: auto"><table><tr><th>Рейтинг</th><th>&nbsp;&nbsp;&nbsp;Дата</th><th>Сообщение</th></tr>';
	foreach ($records as $rec) {
		
		$i = 0;
		$star = '';
			
		while ($i++ < $rec->review_rating) {
			$star .= '<img src="sites\all\themes\detbox\icons\startgold.png">&nbsp';
		}
			
		$i = 0;
		while ($i++ < (5 - $rec->review_rating)) {
			$star .= '<img src="sites\all\themes\detbox\icons\stargrey.png">&nbsp';
		}
		
		$output .= ('<tr><td>' . $star . '</td><td>' . $rec->review_date . '</td><td>' . $rec->review_text . '</td></tr>');
		
	}
	$output .= "</table></div>";
	
	$form['responce']['table2'] = array(
		'#markup' => $output
	);
   
  if (dtbx_sellerinfo_access()) {
	
  
    $form['responce']['shopid'] = array(
      '#type' => 'hidden',
      '#value' =>  $sellerid,
    );
	
	/*$form['responce']['rating']= array(
	  '#type' => 'radios',
	  '#title' => t('рейтинг'),
	  '#options' => array(t('1'), t('2'), t('3'), t('4'), t('5')),
	  /*'#prefix' => '<div class="container-inline">',
	  '#suffix' => '</div>',*/
    //);

	$form['responce']['lrating']= array(
	  '#type' => 'item',
	  '#title' => 'Ваш отзыв',
	  '#prefix' => '<span class="lyourreview"><br>',
	  '#suffix' => '<br></span>'
	  
    );
	
	$form['responce']['rating'] = array(
		'#prefix' => '<div class="container-inline">',
		'#suffix' => '</div>'
	);
	
	$form['responce']['rating']['label'] = array(
	  '#type' => 'item',
	  '#title' => 'Оценка:',
	  '#prefix' => '<div class="lstarreview">',
	  '#suffix' => '</div>'
    );

	$form['responce']['rating']['img'] = array(
	  '#type' => 'item',
	  '#title' => '	<img src="sites/all/themes/detbox/icons/stargrey.png" id="imgstar1">
					<img src="sites/all/themes/detbox/icons/stargrey.png" id="imgstar2">
					<img src="sites/all/themes/detbox/icons/stargrey.png" id="imgstar3">
					<img src="sites/all/themes/detbox/icons/stargrey.png" id="imgstar4">
					<img src="sites/all/themes/detbox/icons/stargrey.png" id="imgstar5">
				',
	  '#prefix' => '<div class="starreview">',
	  '#suffix' => '</div>'
    );
	
	$form['responce']['rating']['img']['#attached']['js'] = array(ctools_attach_js('selectstar', 'dtbx_sellerinfo', 'js'));
	
	$form['responce']['rating']['select'] = array(
		'#type' => 'hidden',
		'#default_value' => 0,
		'#attributes' => array('id' => 'selectrating')
	);


	$form['responce']['responce_text'] = array(
      '#type' => 'textarea',
	  '#title' => t('Текст отзыва:'),      
      '#rows' => 3,
      '#cols' => 10,
	  '#default_value' => '', 
      '#resizable' => TRUE,
	  '#prefix' => '<br>',
    );
	
    $form['responce']['submit'] = array(
	  '#type' => 'submit', 
	  '#value' => t('Отправить'), 
	  '#submit' => array('dtbx_sellerinfo_submit'),
	  '#attributes' => array(
			'class' => array('form-add-review'),
		)	
	);
  
  } 
    	
  return $form;
}


/**
* Page access.
**/

function dtbx_sellerinfo_access() {
  global $user;
  return ($user->uid > 0);
}

function dtbx_sellerinfo_submit($form, &$form_state) {
	global $user;
	$l_user = db_query('select * from t_user where uid = :uid', array(':uid' => $user->uid))->fetchObject();
	db_query('INSERT INTO t_review (review_date, user_id, company_id, review_text, review_rating)
			  VALUES (:review_date, :user_id, :company_id, :review_text, :review_rating)', 
			  array(':review_date' => date("Y-m-d H:i:s", time()), 
				  ':user_id' => $l_user->user_id,
   				  ':company_id' => $form_state['values']['shopid'],
				  ':review_text' => $form_state['values']['responce_text'],
				  ':review_rating' => $form_state['values']['select']));
	drupal_set_message(t('Отзыв добавлен.'), 'status');
	//$form_state['rebuild'] = true;
	//cache_clear_all();					
	//return $form;
}


?>